# Generated by Django 4.2.23 on 2025-06-17 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaserequest_selected_quotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('purchase_date', models.DateField()),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CHECKED_OUT', 'Checked Out'), ('MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('last_maintained', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='supplierperformance',
            options={'ordering': ['-review_date']},
        ),
        migrations.RenameField(
            model_name='supplierperformance',
            old_name='date_evaluated',
            new_name='review_date',
        ),
        migrations.RenameField(
            model_name='supplierperformance',
            old_name='evaluator',
            new_name='reviewed_by',
        ),
        migrations.RenameField(
            model_name='supplierperformance',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='inspection_notes',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='inspection_status',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='rejection_reasons',
        ),
        migrations.RemoveField(
            model_name='supplierperformance',
            name='communication_rating',
        ),
        migrations.RemoveField(
            model_name='supplierperformance',
            name='delivery_timeliness',
        ),
        migrations.RemoveField(
            model_name='supplierperformance',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='supplierperformance',
            name='quality_rating',
        ),
        migrations.RemoveField(
            model_name='supplierperformance',
            name='score',
        ),
        migrations.AddField(
            model_name='supplierperformance',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.purchaseorder'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Routine Maintenance'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('maintenance_date', models.DateField()),
                ('performed_by', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_to', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('checked_out_by', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('checked_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('condition_at_checkout', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('condition_at_return', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20, null=True)),
                ('checkout_notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.assetcategory'),
        ),
    ]
