# Generated by Django 4.2.23 on 2025-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_asset_assetcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcheckout',
            old_name='checked_out_by',
            new_name='checked_out_to_name',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='checked_out_to',
        ),
        migrations.RemoveField(
            model_name='assetcheckout',
            name='notes',
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='checked_out_to_phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
